name: Deployment using Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clear npm cache
        run: npm cache clean --force

      # - name: Install dependencies
      #   run: npm install

      - name: install Vercel
        run: npm install --global vercel@latest

      - name: pull Vercel env info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: build Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: deploy project
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
